-- Seed data: insert demo leads for a new user
-- Run AFTER the schema.sql and after creating a user account

-- Example: Replace 'YOUR_USER_ID' with your Supabase auth user ID
-- You can find it in auth.users table or in the Supabase dashboard

INSERT INTO leads (user_id, title, company, description, budget_min, budget_max, ai_category, skills, contact_name, contact_title, source, location, remote_type, project_type, posted_date, status, score_overall, score_intent, score_budget, score_urgency, score_technical)
VALUES
  ('YOUR_USER_ID', 'AI Agent Development for Customer Support', 'TechCorp Inc', 'Looking for experienced AI engineers to build an autonomous customer support agent using LLMs and RAG architecture.', 75000, 150000, 'AI Agents', ARRAY['AI Agents', 'LLMs', 'RAG', 'Python', 'LangChain'], 'Sarah Chen', 'VP of Engineering', 'linkedin', 'San Francisco, CA', 'remote', 'contract', NOW() - INTERVAL '2 days', 'new', 87, 82, 75, 88, 92),
  ('YOUR_USER_ID', 'Enterprise RAG System', 'DataFlow Systems', 'Build a retrieval-augmented generation system for internal document search across 10M+ documents.', 120000, 250000, 'RAG', ARRAY['RAG', 'Vector Databases', 'LLMs', 'Python', 'Elasticsearch'], 'James Mitchell', 'CTO', 'linkedin', 'New York, NY', 'hybrid', 'contract', NOW() - INTERVAL '1 day', 'qualified', 91, 90, 95, 72, 88),
  ('YOUR_USER_ID', 'ChatGPT-style Customer Portal', 'InnovateTech', 'Need a custom ChatGPT-like interface for our customer portal with domain-specific knowledge base.', 50000, 100000, 'LLMs', ARRAY['LLMs', 'NLP', 'React', 'Python', 'OpenAI API'], 'Emily Rodriguez', 'Product Manager', 'upwork', 'Austin, TX', 'remote', 'freelance', NOW() - INTERVAL '3 days', 'new', 74, 68, 62, 85, 78),
  ('YOUR_USER_ID', 'ML Pipeline Optimization', 'ScaleAI', 'Optimize our existing ML training pipeline to reduce costs by 40% while maintaining model accuracy.', 80000, 160000, 'MLOps', ARRAY['MLOps', 'Kubernetes', 'Python', 'TensorFlow', 'CI/CD'], 'David Park', 'Head of ML', 'linkedin', 'Seattle, WA', 'remote', 'contract', NOW() - INTERVAL '5 days', 'contacted', 79, 75, 80, 65, 82),
  ('YOUR_USER_ID', 'NLP Document Classifier', 'LegalTech Pro', 'Build an NLP system to automatically classify and tag legal documents by type and urgency.', 40000, 80000, 'NLP', ARRAY['NLP', 'Python', 'Transformers', 'Text Classification'], 'Maria Santos', 'Director of Ops', 'linkedin', 'Chicago, IL', 'hybrid', 'freelance', NOW() - INTERVAL '4 days', 'new', 68, 72, 55, 78, 70),
  ('YOUR_USER_ID', 'Conversational AI Platform', 'VoiceFirst', 'Build a multi-turn conversational AI platform with voice integration and real-time transcription.', 150000, 300000, 'Conversational AI', ARRAY['Conversational AI', 'LLMs', 'Speech Recognition', 'Python', 'WebSockets'], 'Alex Thompson', 'CEO', 'linkedin', 'Los Angeles, CA', 'remote', 'contract', NOW() - INTERVAL '6 hours', 'new', 93, 88, 92, 95, 90),
  ('YOUR_USER_ID', 'Computer Vision Quality Control', 'ManufactureAI', 'Implement computer vision system for real-time defect detection on production line.', 60000, 120000, 'Computer Vision', ARRAY['Computer Vision', 'PyTorch', 'Python', 'Edge Computing'], 'Robert Kim', 'VP Manufacturing', 'referral', 'Detroit, MI', 'onsite', 'contract', NOW() - INTERVAL '7 days', 'qualified', 71, 65, 70, 60, 75),
  ('YOUR_USER_ID', 'AI-Powered Search Engine', 'SearchTech', 'Build a semantic search engine using vector embeddings for our e-commerce platform with 5M products.', 90000, 180000, 'NLP', ARRAY['Vector Databases', 'NLP', 'Python', 'Semantic Search', 'AWS'], 'Lisa Wang', 'Engineering Lead', 'linkedin', 'Boston, MA', 'remote', 'contract', NOW() - INTERVAL '10 days', 'proposal', 85, 80, 85, 70, 88);
